// Dummy data for the Safety App

export const dummyUsers = [
  {
    id: 1,
    name: "Admin User",
    email: "admin@company.com",
    password: "1122",
    role: "Admin",
    status: "Active",
    department: "Administration",
    approved: true,
  },
  {
    id: 2,
    name: "Manager User",
    email: "manager@company.com",
    password: "1122",
    role: "Safety Manager",
    status: "Active",
    department: "Operations",
    approved: true,
  },
  {
    id: 3,
    name: "Supervisor User",
    email: "supervisor@company.com",
    password: "1122",
    role: "Supervisor",
    status: "Active",
    department: "Production",
    approved: true,
  },
  {
    id: 4,
    name: "Employee User",
    email: "employee@company.com",
    password: "1122",
    role: "Employee",
    status: "Active",
    department: "Maintenance",
    approved: true,
  },
  {
    id: 5,
    name: "Emilsa User",
    email: "emilsa@company.com",
    password: "1122",
    role: "Supervisor",
    status: "Active",
    department: "Production",
    approved: true,
  },
];

export const dummyTrainings = [
  {
    id: 1,
    title: "Safety Procedures Training",
    type: "Safety",
    description:
      "Comprehensive training on workplace safety procedures and emergency response",
    duration: "2 hours",
    status: "Available",
    assignedTo: "All Employees",
    dueDate: "2024-02-15",
    createdAt: new Date().toISOString(),
    completedBy: [],
  },
  {
    id: 2,
    title: "Hazard Identification Workshop",
    type: "Technical",
    description: "Learn to identify and report workplace hazards effectively",
    duration: "1.5 hours",
    status: "In Progress",
    assignedTo: "All Employees",
    dueDate: "2024-02-20",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    completedBy: [],
  },
  {
    id: 3,
    title: "Fire Safety Training",
    type: "Safety",
    description: "Essential fire safety protocols and evacuation procedures",
    duration: "1 hour",
    status: "Available",
    assignedTo: "All Employees",
    dueDate: "2024-03-01",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    completedBy: [],
  },
  {
    id: 4,
    title: "Equipment Maintenance Certification",
    type: "Technical",
    description: "Proper maintenance and inspection of workplace equipment",
    duration: "3 hours",
    status: "Available",
    assignedTo: "Maintenance Team",
    dueDate: "2024-03-10",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    completedBy: [],
  },
  {
    id: 5,
    title: "OSHA Compliance Overview",
    type: "Compliance",
    description: "Understanding OSHA regulations and compliance requirements",
    duration: "2.5 hours",
    status: "In Progress",
    assignedTo: "Management",
    dueDate: "2024-03-15",
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    completedBy: [],
  },
  {
    id: 6,
    title: "First Aid and CPR Training",
    type: "Safety",
    description: "Basic first aid and CPR skills for emergency situations",
    duration: "4 hours",
    status: "Available",
    assignedTo: "All Employees",
    dueDate: "2024-03-20",
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    completedBy: [],
  },
  {
    id: 7,
    title: "Chemical Handling Safety",
    type: "Safety",
    description: "Safe handling, storage, and disposal of hazardous chemicals",
    duration: "2 hours",
    status: "Completed",
    assignedTo: "Lab Personnel",
    dueDate: "2024-02-28",
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    completedBy: ["John Doe", "Jane Smith"],
  },
  {
    id: 8,
    title: "Ergonomics and Workplace Wellness",
    type: "General",
    description:
      "Preventing injuries through proper ergonomics and wellness practices",
    duration: "1.5 hours",
    status: "Available",
    assignedTo: "Office Staff",
    dueDate: "2024-03-25",
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    completedBy: [],
  },
  {
    id: 9,
    title: "Emergency Response Planning",
    type: "Safety",
    description: "Developing and implementing emergency response plans",
    duration: "3 hours",
    status: "In Progress",
    assignedTo: "Safety Team",
    dueDate: "2024-04-01",
    createdAt: new Date(Date.now() - 691200000).toISOString(),
    completedBy: [],
  },
  {
    id: 10,
    title: "Data Security and Privacy Training",
    type: "Compliance",
    description: "Protecting sensitive data and maintaining privacy standards",
    duration: "2 hours",
    status: "Available",
    assignedTo: "IT Department",
    dueDate: "2024-04-05",
    createdAt: new Date(Date.now() - 777600000).toISOString(),
    completedBy: [],
  },
  {
    id: 11,
    title: "Leadership Safety Communication",
    type: "General",
    description: "Effective communication of safety policies and procedures",
    duration: "2.5 hours",
    status: "Available",
    assignedTo: "Supervisors",
    dueDate: "2024-04-10",
    createdAt: new Date(Date.now() - 864000000).toISOString(),
    completedBy: [],
  },
];

export const dummyHazards = [
  {
    id: 1,
    type: "Slip/Trip",
    location: "Warehouse A",
    severity: "High",
    date: new Date().toISOString().split("T")[0],
    status: "Open",
    description: "Water spill near loading dock",
    reportedBy: "John Doe",
    role: "employee",
    priority: null,
    timeline: null,
    assignedTeam: null,
    approvalRemarks: null,
    adminApproval: null,
    managerApproval: null,
    supervisorApproval: null,
    assignedEmployees: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    type: "Electrical",
    location: "Production Floor",
    severity: "Critical",
    date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    status: "Pending",
    description: "Exposed wiring in machine panel",
    reportedBy: "Jane Smith",
    role: "employee",
    priority: "High",
    timeline: "2024-01-20",
    assignedTeam: "Electrical Team",
    approvalRemarks: "Immediate attention required",
    adminApproval: "approved",
    managerApproval: "approved",
    supervisorApproval: "approved",
    assignedEmployees: [],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 3,
    type: "Chemical",
    location: "Storage Room",
    severity: "Medium",
    date: new Date(Date.now() - 172800000).toISOString().split("T")[0],
    status: "Resolved",
    description: "Improper chemical storage",
    reportedBy: "Bob Johnson",
    role: "employee",
    priority: "Medium",
    timeline: "2024-01-18",
    assignedTeam: "Safety Team",
    approvalRemarks: "Resolved with proper storage procedures",
    adminApproval: "approved",
    managerApproval: "approved",
    supervisorApproval: "approved",
    assignedEmployees: [],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const dummyChecklists = [
  {
    id: 1,
    title: "Daily Safety Inspection",
    department: "Production",
    dueDate: "2024-01-16",
    status: "In Progress",
    items: [
      {
        id: 1,
        text: "Check fire extinguisher pressure",
        completed: true,
      },
      { id: 2, text: "Verify emergency exit signs", completed: true },
      { id: 3, text: "Inspect PPE equipment", completed: false },
      { id: 4, text: "Test emergency alarm system", completed: false },
    ],
  },
  {
    id: 2,
    title: "Weekly Equipment Maintenance",
    department: "Maintenance",
    dueDate: "2024-01-17",
    status: "Pending",
    items: [
      { id: 1, text: "Lubricate machinery parts", completed: false },
      { id: 2, text: "Check hydraulic fluid levels", completed: false },
      { id: 3, text: "Inspect safety guards", completed: false },
    ],
  },
];

export const dummyAlerts = [
  {
    id: 1,
    title: "Fire Drill Scheduled",
    message: "Mandatory fire drill at 2 PM today in the main building.",
    type: "info",
    date: new Date().toISOString(),
    read: false,
  },
  {
    id: 2,
    title: "Safety Meeting Reminder",
    message: "Weekly safety meeting starts in 30 minutes.",
    type: "warning",
    date: new Date(Date.now() - 3600000).toISOString(),
    read: true,
  },
];

export const dummyNotifications = [
  {
    id: 1,
    title: "New Hazard Reported",
    message: "A new hazard has been reported in Warehouse A.",
    type: "alert",
    date: new Date().toISOString(),
    read: false,
  },
  {
    id: 2,
    title: "Training Completed",
    message: "John Doe has completed the Safety Procedures Training.",
    type: "success",
    date: new Date(Date.now() - 7200000).toISOString(),
    read: false,
  },
];

export const dummyUser = {
  id: 1,
  name: "John Doe",
  email: "john@company.com",
  role: "Admin",
};

export const dummyTheme = "light";
